apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullname }}
  namespace: des
  labels:
    app.kubernetes.io/name: notification-service  # Etiqueta con valor plano
    app.kubernetes.io/instance: instance-001  # Etiqueta con valor plano
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: notification-service  # Etiqueta con valor plano
    app.kubernetes.io/instance: instance-001  # Etiqueta con valor plano

