apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notification-service-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "git@github.com:DaniCuesta/notification-service-app.git"
    targetRevision: "main"
    path: "helm"
    helm:
      valueFiles:
        - values-des.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "des"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
