replicaCount: 1

fullname: notification-service  # Nombre completo para reutilizar en metadata

image:
  repository: quay.io/danicuestam/notification-service
  pullPolicy: IfNotPresent
  tag: "v1.0.0"

service:
  type: ClusterIP
  port: 8084

resources:
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"

labels:
  app.kubernetes.io.name: notification-service
  app.kubernetes.io.instance: "{{ .Release.Name }}"  # Esto se evaluará en tiempo de ejecución
